<main>
	<section>
		<?php foreach($articles as $article): ?>
			
			<article class="articleAccueil">
				<div class="titre">
					<h2><a href="index.php?page=article&idArticle=<?= $article['id'] ?>"><?= $article['title'] ?></a></h2>
					<p><strong>Dans la catégorie :</strong> <a href="index.php?page=category&idCategory=<?= $article['id_category'] ?>"><?= $article['name'] ?></a></p>
				</div>
				<a href="index.php?page=article&idArticle=<?= $article['id'] ?>"><img src="<?= $article['image'] ?>"></img></a>
				<p class="description"><?= $article['description'] ?>... <a href="index.php?page=article&idArticle=<?= $article['id'] ?>">Lire la suite</a></p>
				
				<p>Rédigé par <a href="index.php?page=writer&idWriter=<?= $article['id_writer'] ?>">
					<?= $article['first_name'] ?> <?= $article['last_name'] ?></a>, le <?= $article['publication_date'] ?></p>
			</article>
			
		<?php endforeach; ?>
	</section>
</main>
