<main>
    <section class="connexion">
    	<form method="post" autocomplete="on">
    		<p>
    			<label for='identifiant'>Adresse Email</label>
    		</p>
    		<p>	
    			<input type="text" name="identifiant" id="identifiant">
    		</p>
    		<p>
    			<label for='pw'>Mot de passe</label>
    		</p>
    		<p>	
    			<input type="password" name="pw" id="pw">
    		</p>
    		<button>Se connecter</button>
    		<p class="erreur"><?= $message ?></p>
    	</form>
	</section>
</main>