<main class="pageDashboard">
    <aside class="gestions">
        <div>
            <a href="index.php?page=dashboard"><h3><i class="far fa-newspaper"></i>  Gestion des articles</h3></a>
            <a href="index.php?page=comments"><h3><i class="fas fa-comments"></i>  Gestion des commentaires</h3></a>
            <a href="index.php?page=dashboardCategories"><h3><i class="fas fa-tags"></i>  Gestion des catégories</h3></a>
            <a href="index.php?page=writers"><h3><i class="fas fa-pen-nib"></i>  Gestion des auteurs</h3></a>
        </div>
    </aside>
	<section class="dashboard dashboardCategories">
	    <h1>Gestion des catégories</h1>
	    <form method='post'>
	        <label for="category">Créer une nouvelle catégorie</label>
	        <input type="text" name="category" id="category"/>
	        <input type="submit" value="Créer"/>
	    </form>
	    <table>
    	    <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Nombre d'articles</th>
            </tr>
            <?php foreach($categories as $category): ?>
    	    <tr>
    	    	<td><?= $category['id'] ?></td>
    	    	<?php if(isset($_GET['idModif']) && $_GET['idModif'] == $category['id']): ?>
    	    	    <td><form method="post"><input type="text" name="name" value="<?= $category['name'] ?>"><button type="submit">Modifier</button></form></td>
    	    	<?php else: ?>
    			    <td><?= $category['name'] ?></td>
    			<?php endif; ?>
    			<td><?= countArticlesByCategory($category['id'])['count'] ?></td>
    			<td><button><a href="index.php?page=dashboardCategories&idModif=<?= $category['id'] ?>"><i class="fas fa-pen-nib"></i></a></button></td>
    			
    			<td><button onclick="confirmDeleteCategory()"><a href="index.php?page=dashboardCategories&idDeleteCategory=<?= $category['id'] ?>"><i class="fas fa-trash-alt"></i></a></button></td>
    	    </tr>
    	    <?php endforeach; ?>
	    </table>
	</section>
</main>