<main class="pageDashboard">
    <aside class="gestions">
        <div>
            <a href="index.php?page=dashboard"><h3><i class="far fa-newspaper"></i>  Gestion des articles</h3></a>
            <a href="index.php?page=comments"><h3><i class="fas fa-comments"></i>  Gestion des commentaires</h3></a>
            <a href="index.php?page=dashboardCategories"><h3><i class="fas fa-tags"></i>  Gestion des catégories</h3></a>
            <a href="index.php?page=writers"><h3><i class="fas fa-pen-nib"></i>  Gestion des auteurs</h3></a>
        </div>
    </aside>
	<section class="dashboard dashboardCategories">
	    <h1>Gestion des auteurs</h1>
	    <a href="index.php?page=newWriter"><button>Ajouter un nouvel auteur</button></a>
	    <table>
    	    <tr>
                <th>ID</th>
                <th>Auteur</th>
                <th>Nombre d'articles</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach($writers as $writer): ?>
    	    <tr>
    	    	<td><?= $writer['id'] ?></td>
    			<td><?= $writer['first_name'] ?> <?= $writer['last_name'] ?></td>
    			<td><?= countArticlesByWriter($writer['id'])['count'] ?></td>
    			<td><button><a href="index.php?page=newWriter&idModif=<?= $writer['id'] ?>"><i class="fas fa-pen-nib"></i></a></button></td>
    			<td><button onclick="confirmDeleteWriter()"><a href="index.php?page=writers&idDeleteWriter=<?= $writer['id'] ?>"><i class="fas fa-trash-alt"></i></a></button></td>
    			
    	    </tr>
    	    <?php endforeach; ?>
	    </table>
	</section>
</main>