<main>
	<section>
		<?php foreach($allArticles as $article): ?>
			<article class="articleListe">
				<div class="titre">
					<h2><a href="index.php?page=article&idArticle=<?= $article['id'] ?>"><?= $article['title'] ?></a></h2>
					<p><strong>Dans la catégorie :</strong> <?= $article['name'] ?></p>
				</div>
				<img src="<?= $article['image'] ?>"></img>
				<p class="description"><?= $article['description'] ?>... <a href="index.php?page=article&idArticle=<?= $article['id'] ?>">Lire la suite</a></p>
				
				<p>Rédigé par <strong><?= $article['first_name'] ?> <?= $article['last_name'] ?></strong>, le <?= $article['publication_date'] ?></p>
			</article>
		<?php endforeach; ?>
	</section>
</main>
