<main>
    <section class="newArticle">
    	<h1>Rédiger un article</h1>
    	<form method="post" enctype="multipart/form-data">
      		<p>
    			<label for='firstName'>Prénom</label>
    			<input type="text" name="firstName" id="firstName" value="<?= (isset($_GET['idModif'])) ? $writer['first_name'] : "" ?>">
    		</p>
    		<p>
    			<label for='lastName'>Nom</label>
    			<input type="text" name="lastName" id="lastName" value="<?= (isset($_GET['idModif'])) ? $writer['last_name'] : "" ?>">
    		</p>
    		<p>
    			<label for='pseudo'>Pseudo</label>
    			<input type="text" name="pseudo" id="pseudo" value="<?= (isset($_GET['idModif'])) ? $writer['pseudo'] : "" ?>">
    		</p>
    		<p>
    			<label for='email'>Adresse email</label>
    			<input type="email" name="email" id="email" value="<?= (isset($_GET['idModif'])) ? $writer['email'] : "" ?>">
    		</p>
    		<button type="submit"><?= (isset($_GET['idModif'])) ? "Modifier l'auteur" : "Ajouter un nouvel auteur" ?></button>
    	</form>
	</section>
</main>